name: 'Pot File Generator For WordPress'
description: 'This Action Generates POT Files for your wordpress Plugin / Theme based on the content inside Github Repo'
author: 'varunsridharan'
branding:
  icon: 'edit'
  color: 'gray-dark'

inputs:
  save_path:
    description: 'Location / Path to save POT File Required'
    default: './'
    required: false
  item_slug:
    description: 'Slug of your WordPress Theme / Plugin Slug Required'
    default: ''
    required: false
  domain:
    description: 'WordPress Theme / Plugin TextDomain'
    required: false
  package_name:
    description: 'WordPress Theme / Plugin Name'
    required: false
  headers:
    description: 'Array in JSON format of custom headers which will be added to the POT file. Defaults to empty array.'
    required: false
  exclude:
    description: 'Comma separated list of custom paths to exclude from the POT file.'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.save_path }}
    - ${{ inputs.item_slug }}
    - ${{ inputs.domain }}
    - ${{ inputs.package_name }}
    - ${{ inputs.headers }}
    - ${{ inputs.exclude }}
